THM-Health/PILOS

CHANGELOG.md
app/Http/Controllers/api/v1/RoomController.php
app/Http/Controllers/api/v1/RoomFileController.php
app/Http/Controllers/api/v1/RoomMemberController.php
resources/js/api/base.js
resources/js/app.js
resources/js/components/Room/FileComponent.vue
resources/js/components/Room/MembersComponent.vue
resources/js/components/Room/NewRoomComponent.vue
resources/js/components/Room/SettingsComponent.vue
resources/js/lang/de/app.js
resources/js/lang/de/rooms.js
resources/js/lang/en/rooms.js
resources/js/router.js
resources/js/views/rooms/Index.vue
resources/js/views/rooms/View.vue
resources/lang/de/app.php
resources/lang/en/app.php
resources/sass/app.scss
tests/Feature/api/v1/Room/MembershipTest.php
tests/Frontend/api/base.spec.js
tests/Frontend/components/Room/NewRoom.spec.js
tests/Frontend/components/Room/RoomList.spec.js

- **Bugfix**
- Feature
- **Refactoring (e.g. Style updates, Test implementation, etc.)**
- 
- 
- 
-

Improve error message handling

---

app/Http/Controllers/api/v1/MeetingController.php
app/Http/Controllers/api/v1/RoomController.php
app/Meeting.php
database/factories/RoomType.php
tests/Feature/api/v1/Room/FileTest.php
tests/Feature/api/v1/Room/RoomTest.php

- **Bugfix**
- Feature
- Fixes wrong end meeting callback salt calculation and check

Fix wrong end meeting callback salt

---

CHANGELOG.md
app/Http/Controllers/api/v1/RoomController.php
app/Http/Controllers/api/v1/RoomTypeController.php
config/settings.php
resources/js/components/Room/NewRoomComponent.vue
resources/js/components/Room/RoomComponent.vue
resources/js/lang/de/app.js
resources/js/lang/en/app.js
resources/js/views/rooms/Index.vue
resources/sass/app.scss
routes/api.php
tests/Feature/api/v1/Room/RoomTest.php
tests/Feature/api/v1/Room/RoomTypeTest.php
tests/Frontend/components/Room/NewRoom.spec.js
tests/Frontend/components/Room/RoomList.spec.js

- Bugfix
- **Feature**
- Change loading of room data to mounted to improve navigation speed
- Add pagination to room list (own and shared rooms)
- Added seach for rooms
*none*

Add pagination to room list

---

app/Http/Controllers/api/v1/auth/LoginController.php
app/Listeners/SetDefaultRoleForLdapUser.php

- **Bugfix**
- Feature
- Change ldap guard to stay bound
- Change role listener to load user again

Fix ldap role load

---

resources/js/app.js

- **Bugfix**
- Feature
- Clear current user on 401 error and redirect only once to login page

Clear current user in frontend on 401 error

---

.github/workflows/ci.yml

- Bugfix
- Feature
- Added cache for npm and composer
- Changed xdebug to pcov 
- Make code coverage only for php 7.3 (shouldn't be required to run on multiple php versions)

Improve GitHub action performance

---

.github/workflows/ci.yml
composer.json
composer.lock
package-lock.json
resources/js/views/settings/roles/View.vue
resources/js/views/settings/users/View.vue
resources/sass/app.scss
tests/Frontend/views/settings/roles/View.spec.js
tests/Frontend/views/settings/users/View.spec.js

- Bugfix
- Feature
- **Refactoring (e.g. Style updates, Test implementation, etc.)**
- Added loading overlay for roles view page
- Added error handling during load and persist for roles view page
- Added loading overlay for users view page
- Added error handling during load and persist for users view page
- Added check that only the profile page for the own user can be opened

79 add loading error overlay

---

resources/js/lang/de/app.js
resources/js/lang/en/app.js
resources/js/views/settings/roles/View.vue

- **Bugfix**
- Feature
- Added missing translation files
- Implemented checkbox as slot

Add missing translation and fix lang. not changed

---

resources/js/lang/de/settings.js
resources/js/lang/en/settings.js
resources/js/store/modules/session.js
resources/js/views/settings/roles/View.vue
resources/js/views/settings/roomTypes/View.vue
resources/js/views/settings/users/View.vue
resources/lang/de/validation.php
resources/lang/en/validation.php

- **Bugfix**
- Feature
- Clear validation errors on successful save

Clear validation errors on successful save

---

app/Http/Requests/RoleRequest.php
tests/Feature/api/v1/RoleTest.php

- **Bugfix**
- Feature
- Changed form validation to allow roles without permissions

Fix role requires at least one permission

---

CHANGELOG.md
resources/js/api/base.js
tests/Frontend/api/base.spec.js

- **Bugfix**
- Feature
- Fix invalid mutation type in base error handling function

Bugfix vuex unknown mutation type

---

CHANGELOG.md
app/Http/Controllers/api/v1/ApplicationController.php
app/Http/Requests/UpdateSetting.php
app/Http/Resources/ApplicationSettings.php
config/settings.php
resources/js/components/LocaleSelector.vue
resources/js/lang/de/app.js
resources/js/lang/de/settings.js
resources/js/lang/en/app.js
resources/js/lang/en/settings.js
resources/js/views/App.vue
resources/js/views/settings/Application.vue
resources/lang/de/validation.php
resources/lang/en/validation.php
resources/sass/app.scss
tests/Feature/api/v1/SettingsTest.php
tests/Frontend/components/LocaleSelector.spec.js
tests/Frontend/views/settings/Application.spec.js

- Bugfix
- **Feature**
- Added configurable help link to navigation bar
- Fixed wrong baseline of locale selector in navigation bar

Add configurable help link

---

CHANGELOG.md
resources/js/lang/de/rooms.js
resources/js/lang/en/rooms.js
resources/js/views/rooms/View.vue
tests/Frontend/views/rooms/View.spec.js

- **Bugfix**
- Feature
- Adjusted invalid access code error message
- Fixed error on empty access code

Bugfix error on empty access code

---

.env.example
CHANGELOG.md
MIGRATE_GREENLIGHT.md
config/greenlight.php
routes/web.php

- Bugfix
- **Feature**
- **Documentation**
- Add support for common greenlight urls: room urls, /ldap_signin, /signin and /default_room
- Add migration guide

Greenlight compatibility mode

---

CHANGELOG.md
app/Http/Resources/UserSearch.php
resources/js/components/Room/MembersComponent.vue
tests/Feature/api/v1/UserTest.php
tests/Frontend/components/Room/RoomMembers.spec.js

- Bugfix
- **Feature**
- Add email to user search

Add email to user search

---

CHANGELOG.md
app/Room.php
resources/views/vendor/notifications/email.blade.php

- **Bugfix**
- Feature
- Fixed missing slash in logo url in email template
- Fixed missing slash in room join url in bbb room

Add missing slash

---

app/Meeting.php
composer.json
composer.lock

- Bugfix
- Feature
- **Other** (please describe): Update dependencies (bbb api)
- Updated bbb api to v4.0.0

Update bbb api to v4.0.0

---

CHANGELOG.md
resources/js/components/Room/FileComponent.vue
resources/js/components/Room/HistoryComponent.vue
resources/js/components/Room/MembersComponent.vue
resources/js/components/Room/SettingsComponent.vue
resources/js/components/Room/TokensComponent.vue
resources/js/components/RoomType/RoomTypeSelect.vue
resources/js/lang/de/app.js
resources/js/lang/de/meetings.js
resources/js/lang/de/rooms.js
resources/js/lang/de/settings.js
resources/js/lang/en/app.js
resources/js/lang/en/meetings.js
resources/js/lang/en/rooms.js
resources/js/lang/en/settings.js
resources/js/views/rooms/Index.vue
resources/js/views/rooms/OwnIndex.vue
resources/js/views/rooms/View.vue
tests/Frontend/components/Room/History.spec.js
tests/Frontend/components/Room/NewRoom.spec.js
tests/Frontend/components/RoomType/RoomTypeSelect.spec.js

- Bugfix**
- Feature
- Other (please describe): Improve accessibility
- Add tooltips to more buttons

Improve accessibility

---

CHANGELOG.md
app/Http/Controllers/api/v1/ApplicationController.php
app/Http/Controllers/api/v1/UserController.php
app/Http/Resources/Room.php
app/Http/Resources/User.php
app/User.php
resources/js/lang/de/settings.js
resources/js/lang/en/settings.js
resources/js/views/settings/users/Index.vue
tests/Feature/api/v1/UserTest.php
tests/Frontend/views/settings/users/Index.spec.js

- Bugfix
- **Feature**
- Display roles in user list
- Add filter to show only users of a particular group in user list

Add role filter to users list

---

.babelrc
.eslintrc.js
CHANGELOG.md
package-lock.json
package.json
resources/js/components/Room/BrowserNotification.vue
resources/js/lang/de/rooms.js
resources/js/lang/en/rooms.js
resources/js/views/rooms/View.vue
tests/Frontend/components/Room/BrowserNotification.spec.js

- Bugfix
- **Feature**
- Add browser notifications on room start

Add browser notifications on room start

---

CHANGELOG.md
app/Http/Resources/Server.php
app/Server.php
composer.json
composer.lock
database/factories/ServerFactory.php
database/migrations/2022_03_17_104929_add_version_to_servers_table.php
resources/js/lang/de/settings.js
resources/js/lang/en/settings.js
resources/js/views/settings/servers/Index.vue
resources/js/views/settings/servers/View.vue
tests/Feature/api/v1/Room/RoomTest.php
tests/Feature/api/v1/ServerTest.php
tests/Fixtures/GetApiVersion-Disabled.xml
tests/Fixtures/GetApiVersion.xml
tests/Frontend/views/settings/servers/Index.spec.js
tests/Frontend/views/settings/servers/View.spec.js
tests/Unit/ServerTest.php

- Bugfix
- **Feature**
- Add bbb version to server list and view
*none*

Show BBB version

---

CHANGELOG.md
app/Http/Controllers/api/v1/ServerController.php
tests/Feature/api/v1/ServerTest.php

- **Bugfix**
- Feature
- Fix bbb version sorting in server list

Bugfix version sorting in server list

---

CHANGELOG.md
app/Http/Requests/CreateRoom.php
app/Http/Requests/UpdateRoomSettings.php
app/Rules/ValidRoomType.php
app/Services/RoomTestHelper.php
database/factories/RoomFactory.php
tests/Feature/api/v1/Room/RoomTest.php

- **Bugfix**
- Feature
- Require room name length of > 1
- Fix bug causing server error 500 if room type was invalid

Change room name length

---

.github/workflows/ci.yml
.php-cs-fixer.php
CHANGELOG.md
app/Console/Commands/ImportGreenlight.php
app/Enums/CustomStatusCodes.php
app/Enums/LinkButtonStyle.php
app/Enums/LinkTarget.php
app/Enums/RoomLobby.php
app/Enums/RoomUserRole.php
app/Enums/ServerStatus.php
app/Http/Controllers/api/v1/auth/LoginController.php
app/Http/Controllers/api/v1/auth/ResetPasswordController.php
app/Room.php
app/Rules/ValidName.php
app/Server.php
app/ServerPool.php
composer.json
composer.lock
tests/Feature/api/v1/Room/AttendanceExcelImport.php
tests/Feature/api/v1/Room/RoomStatisticTest.php
tests/Feature/api/v1/SettingsTest.php

- Bugfix
- Feature
- **Other** (please describe):  Upgrade to php 8.1
- Change composer min. php version to 7.4
- Add support for php 8.1
- Upgrade php-cs-fixer to support php 8.1

Upgrade to php8.1

---

CHANGELOG.md
resources/js/views/settings/serverPools/Index.vue

- **Bugfix**
- Feature
- Fix tooltip covering view/edit button of server pool overview list

Fix tooltip ui bug

---

CHANGELOG.md
resources/js/views/settings/serverPools/Index.vue

- **Bugfix**
- Feature
- Backport #246

Backport Fix tooltip ui bug

---

.eslintignore
CHANGELOG.md
app/Room.php
jest.config.js
lang/de/rooms.php
lang/en/rooms.php
resources/custom/.gitignore
resources/js/components/Features.vue
resources/js/lang/de/rooms.js
resources/js/lang/en/rooms.js
resources/js/router.js
resources/js/views/App.vue
resources/js/views/Home.vue
resources/js/views/rooms/View.vue
webpack.mix.js

- Bugfix
- **Feature**
- Move feature section of the welcome page to seperate component
- Load welcome view, feature and footer component via absolute paths to allow override via custom path resolver in webpack
- Use application name in join room link
To override the welcome via, feature component, etc. copy the file from e.g. resources/js/**views/Home.vue** to resources/custom/js/**views/Home.vue**.
**Note**: The highlighted path and filename needs to stay the same.

Overwrite welcome page and footer

---

.env.ci
.env.example
CHANGELOG.md
CONTRIBUTING.md
README.md
UPGRADE.md
app/Http/Controllers/api/v1/auth/LoginController.php
config/ldap.php
docker-compose.yml
docker/openldap/acl.ldif
docker/openldap/bootstrap.ldif

- Bugfix
- **Feature**
- Add openldap and phpldapadmin to local docker-compose/sail environment
- Add default users and groups in ldap
- Update contributing docs
- Changed ldap role mapping syntax to json

Add local openldap for dev

---

CHANGELOG.md
README.md
docker/8.1/000-default.conf
docker/8.1/Dockerfile
docker/8.1/ldap/ldap.conf
docker/8.1/php.ini
docker/8.1/php/php.ini
docker/8.1/php/zz-docker.conf
docker/8.1/start-container
docker/8.1/supervisord.conf

- Bugfix
- Feature
- Replace php built-in web server with php-fpm and apache

Replace php built-in web server with php-fpm and apache

---

CHANGELOG.md
resources/js/components/Room/AdminComponent.vue
resources/js/components/Room/MembersComponent.vue
resources/js/components/Room/TokensComponent.vue
resources/js/views/App.vue
resources/js/views/Login.vue
resources/js/views/settings/serverPools/Index.vue
resources/js/views/settings/servers/Index.vue
resources/js/views/settings/users/Index.vue
resources/sass/app/_welcome.scss
resources/sass/base.scss
resources/sass/override/_background.scss
resources/sass/override/_badges.scss
resources/sass/override/_nav.scss
resources/sass/theme/default/_variables.scss
resources/sass/theme/thm/_variables.scss

- **Bugfix**
- Feature
- Fix error in color customization / themes
- Remove enforced white text with .text-white

251 Bugfix color customization

---

.github/workflows/ci.yml

- Bugfix
- Feature
- **Refactoring** (e.g. Style updates, Test implementation, etc.): CI
- Replace codecov bash uploader with github action

Change codecov upload ci

---

CHANGELOG.md
resources/js/views/settings/users/View.vue
tests/Frontend/views/settings/users/View.spec.js

- **Bugfix**
- Feature
- Fixed missing default profile image on new user
- Added test

Fix missing default profile image on new user

---

CHANGELOG.md
database/seeders/RolesAndPermissionsSeeder.php
database/seeders/RoomTypeSeeder.php
database/seeders/RoomTypeSeederV1.php
database/seeders/ServerPoolSeeder.php
database/seeders/ServerSeeder.php
tests/Unit/Console/ImportGreenlightTest.php
tests/Unit/Seeder/RolesAndPermissionsSeederTest.php

- Bugfix
- Feature
- **Other** (please describe): Default settings
- Add default user role on fresh install
- Use english naming for default server pool and room types

Add generic default roles, room types and server pools

---

CHANGELOG.md
docker/app/Dockerfile

- **Bugfix**
- Feature
- Add missing php driver for postgres

Add php postgres drivers

---

CHANGELOG.md
resources/js/components/Room/MembersComponent.vue

- **Bugfix**
- Feature
- Fix error on logout if room member list is shown

Bugfix error on logout if room member list is shown

---

CHANGELOG.md
resources/js/views/settings/Application.vue

- **Bugfix**
- Feature
- Fixed bugged application settings page after uploading new favicon.

Fix Favicon bug

---

CHANGELOG.md
docker-compose-dev.yml

- **Bugfix**
- Feature
- Fixed error in docker-compose-dev.yml leads to deletion of the database in the development environment
Added named volume to db service

Fix error in docker-compose

---

.env.ci
.env.example
CHANGELOG.md
INSTALL.md
app/Http/Middleware/TrustProxies.php
config/app.php
docker-compose-dev.yml
docker-compose.yml

- **Bugfix**
- Feature
- Added support for trusted proxies

Add support for trusted proxies

---

CHANGELOG.md
routes/api.php
tests/Feature/api/v1/Room/FileTest.php
tests/Feature/api/v1/Room/MembershipTest.php
tests/Feature/api/v1/Room/RoomTokenTest.php
tests/Feature/api/v1/SessionTest.php

- Bugfix
- Feature
- Fix inconsistent backend route names

Fix inconsistent backend route names

---

CHANGELOG.md
resources/js/router.js
resources/js/views/App.vue
resources/js/views/Home.vue

- Bugfix
- Feature
- Fixed support to override welcome page, feature component and footer

Add support to override welcome page, feature component and footer

---

CHANGELOG.md
CONTRIBUTING.md
resources/js/i18n.js

- **Bugfix**
- Feature
- Fix override locales

Fix override locales

---

CHANGELOG.md
docker/app/entrypoint
docker/app/scheduler/run.sh
docker/app/scheduler/supervisord.conf
docker/app/supervisord/supervisord.conf

- **Bugfix**
- Feature
- Add composer cache optimization in prod env
- Add laravel view caching in prod env
- Add laravel route caching in prod env
- Add laravel config caching in prod env

Fix scheduler in prod env

---

CHANGELOG.md
app/Console/Commands/UpgradeDatabaseCommand.php

- **Bugfix**
- Feature
- Added `--force` to artisan command to ensure running of db:upgrade in prod env

Fix broken db:upgrade in prod env

---

.github/workflows/ci.yml
CHANGELOG.md
UPGRADE.md
app/Console/Commands/ImportDatabaseCommand.php
app/Console/Kernel.php
app/Exceptions/Handler.php
app/Http/Controllers/Controller.php
app/Http/Kernel.php
app/Http/Middleware/Authenticate.php
app/Providers/AppServiceProvider.php
app/Providers/AuthServiceProvider.php
app/Providers/BroadcastServiceProvider.php
app/Providers/EventServiceProvider.php
app/Providers/RouteServiceProvider.php
composer.json
composer.lock
config/auth.php
config/logging.php
config/mail.php
docker/app/Dockerfile
phpunit.xml
routes/api.php
routes/web.php
tests/Feature/api/v1/Room/MembershipTest.php
tests/Feature/api/v1/Room/RoomTest.php
tests/Fixtures/invalidDatabase.sql
tests/Fixtures/validDatabase.sql
tests/Unit/Console/ImportDatabaseTest.php
tests/Unit/Console/UpgradeDatabaseTest.php

- Bugfix
- **Feature**
- Upgrade to Laravel 10
- Add artisan command to migrate database dump file

Simplify import from mysql database v1

---

CHANGELOG.md
resources/js/views/rooms/Index.vue

- **Bugfix**
- Feature
- Fix broken layout in safari for room search / all rooms

Fix broken layout in safari

---

CHANGELOG.md
resources/js/components/LocaleSelector.vue
resources/js/stores/loading.js
resources/js/views/App.vue
tests/Frontend/components/LocaleSelector.spec.js

- **Bugfix**
- Feature
- Fix room auth error on lang change
- Add loading overlay without remounting components

Fix room auth error on lang change

---

.github/workflows/ci-docker.yml
.gitignore
CHANGELOG.md
app/Http/Resources/ApplicationSettings.php
config/app.php
lang/de.json
lang/en.json
resources/js/components/FooterComponent.vue
tests/Feature/api/v1/SettingsTest.php
tests/Frontend/components/Footer.spec.js

- Bugfix
- **Feature**
- Show app version in footer

Add version to footer

---

CHANGELOG.md
resources/js/components/Room/MembersComponent.vue
routes/api.php
tests/Frontend/components/Room/RoomMembersBulkTest.spec.js

- Bugfix
- Feature
- Changed routes for bulk edit and bulk delete of RoomMembers to new API specification

Change bulk routes to new API specification

---

CHANGELOG.md
resources/js/components/Room/TokensComponent.vue
tests/Frontend/components/Room/RoomToken.spec.js

- **Bugfix**
- Feature
- Fix error showing old validation error in personalized room links modal

Fix error showing old validation error in personalized room links modal

---

CHANGELOG.md
app/Models/IncludedPermissionPermission.php
app/Models/Permission.php
app/Models/PermissionRole.php
app/Models/Role.php
app/Models/User.php

- Bugfix
- Feature
- **Refactoring** (e.g. Style updates, Test implementation, etc.): **Performance**
- Add cache for user permissions
- Add event hooks on all relationship pivot tables that are relevant for the user permissions that clear the cache on any change
**Example loading a room**
_Before_
_After_

Add cache for user permissions

---

app/Http/Controllers/api/v1/RoomController.php
app/Http/Middleware/RoomAuthenticate.php
app/Http/Requests/StartJoinMeeting.php
app/Http/Resources/Room.php
app/Models/Room.php
app/Providers/AppServiceProvider.php
app/Services/MeetingService.php
app/Services/RoomAuthService.php

- Bugfix
- Feature
- **Refactoring** (e.g. Style updates, Test implementation, etc.): **Readability**
- Add global service class to store the auth. status and room token of a request (via RoomAuthenticate Middleware)
- Remove passing auth. status and room token through the code base via the request
This should make the code more easy to understand and maintain

Refactor room auth.

---

CHANGELOG.md
app/Console/Commands/CheckDatabaseConnection.php
docker/app/entrypoint
docs/INSTALL.md

- Bugfix
- **Feature**
- Adjust docker entrypoint to use a custom database connection script
- Add docs on how to use PostgreSQL

Add support for PostgreSQL

---

CHANGELOG.md
app/Console/Commands/ImportDatabaseCommand.php
docker/app/Dockerfile

- Bugfix
- **Feature**
- Add support for postgres database on db:import command

Add support for postgres database on db:import command

---

CHANGELOG.md
resources/js/components/Inputs/RoomTypeSelect.vue
tests/Frontend/components/Input/RoomTypeSelect.spec.js
tests/Frontend/components/Room/NewRoom.spec.js

- **Bugfix**
- Feature
- Refactor roomType select to rely for the selected state on the id of the selected roomtype and not the whole object

Refactor roomType select

---

.env.example
CHANGELOG.md
app/Http/Resources/ApplicationSettings.php
config/app.php
resources/js/components/FooterComponent.vue
tests/Feature/api/v1/SettingsTest.php
tests/Frontend/components/Footer.spec.js

- Bugfix
- **Feature**
- Show name of the product and link to Github project in the footer
This link can be disabled by setting the .env option `WHITELABEL=true`

Add product info to footer

---

CHANGELOG.md
app/Models/Room.php
tests/Unit/MeetingTest.php

- **Bugfix**
- Feature
- Fix moderator only message missing link and access code

Fix moderator only message

---

CHANGELOG.md
resources/js/components/Room/TokensComponent.vue
tests/Frontend/components/Room/RoomInvitation.spec.js
tests/Frontend/components/Room/RoomToken.spec.js

- **Bugfix**
- Feature
- Remove $copyText (missed during the removal of vue-clipboard2 in PILOS v2.3.2) and replaced with native implementation

Fix error copying personalized room link

---

tests/Frontend/components/Room/RoomFile.spec.js

- Bugfix
- Feature
- **Refactoring (e.g. Style updates, Test implementation, etc.)**
- Add test for reload on EventBus message

Add EventBus tests for Room File

---

.github/workflows/ci.yml
docker/app/Dockerfile

- Update to bookworm
- Remove python2
- Change CI php version to 8.3

Update docker base image

---

CHANGELOG.md
app/Services/MeetingService.php
composer.lock
package-lock.json

- Bugfix
- Feature
- Other (please describe): Dependencies
- Bump dependencies

Bump dependencies

---

CHANGELOG.md
resources/js/components/RoomTabFiles.vue
resources/js/components/RoomTabSection.vue
resources/sass/app/_menu.scss
resources/sass/app/app.scss

- Bugfix
- Feature
- Refactor room tab switcher

Refactor room tabs

---

CHANGELOG.md
resources/js/components/RoomTabSection.vue

- Bugfig
- **Feature**
- Save current room tab in url to preserve selected tab on reload

Save current room tab on reload

---

resources/js/views/rooms/Index.vue

- **Bugfix**
- Feature
- Fixes pagination issue added with the UI refactoring

Fix pagination on room index page

---

app/Models/Room.php
app/Services/ServerService.php
database/factories/MeetingFactory.php
tests/Feature/api/v1/Room/RoomTest.php
tests/Integration/api/v1/RoomFileTest.php
tests/Integration/api/v1/RoomTest.php

- **Bugfix**
- Feature
- Fix bug causing the room live stats to be cleared

Bugfix room live stats

---

app/Models/RoomToken.php

- **Bugfix**
- Feature
- Cast global setting before passing it to carbon

Fix error on loading personalized room links

---

app/Http/Controllers/api/v1/RoomController.php
app/Http/Controllers/api/v1/RoomFileController.php
app/Policies/RoomPolicy.php
lang/de/app.php
lang/en/app.php
lang/fr/app.php
routes/api.php
tests/Feature/api/v1/Room/FileTest.php

- Bugfix
- Feature
- Cleanup unused code
- Refactor permission checks for room actions and file access

Cleanup code

---

.github/workflows/ci.yml

Fix ci, install order

---

.env.ci
.env.example
.github/workflows/ci.yml
.github/workflows/pull-locales.yml
.github/workflows/upload-locales.yml
CHANGELOG.md
app/Console/Commands/ImportDatabaseCommand.php
config/database.php
config/queue.php
config/telescope.php
database/migrations/2023_06_07_000001_create_pulse_tables.php
docker-compose-dev.yml
docker-compose.yml
docs/docs/administration/03-configuration.md
docs/docs/administration/05-upgrade.md
docs/docs/administration/07-advanced/03-scaling.md
tests/Utils/create-mariadb-testing-database.sh

- Bugfix
- Feature
- Other (please describe): Bump docker compose services
- Bump mariadb 10 to 11
- Bump phpmyadmin
- Replace mailhog (dead project) with mailpit

Update docker compose services

---

CHANGELOG.md
app/Console/Commands/UpgradeDatabaseCommand.php
app/Http/Controllers/api/v1/ApplicationController.php
app/Http/Requests/UpdateSetting.php
app/Http/Resources/ApplicationSettings.php
app/Settings/GeneralSettings.php
database/settings/2024_05_24_135649_add_toast_life_time_to_general_settings.php
docs/docs/administration/05-upgrade.md
lang/de/settings.php
lang/de/validation.php
lang/en/settings.php
lang/en/validation.php
resources/js/composables/useToast.js
resources/js/stores/settings.js
resources/js/views/settings/Config.vue
tests/Feature/api/v1/SettingsTest.php
tests/Unit/Console/UpgradeDatabaseTest.php

- Bugfix
- **Feature**
- Add setting to change the lifetime of toast messages
- Fixed issue in db:upgrade command causing issues with settings added after the db upgrade

Add setting to change the toast lifetime

---

.eslintignore
.eslintrc.json
package-lock.json
package.json
tests/Frontend/e2e/GeneralApplication.cy.js
tests/Frontend/e2e/Login.cy.js
tests/Frontend/e2e/RoomsIndex.cy.js
tests/Frontend/e2e/RoomsViewGeneral.cy.js
tests/Frontend/support/commands.js
tests/Frontend/support/component.js
tests/Frontend/support/e2e.js
tests/Frontend/support/utils/interceptIndefinitely.js

- Bugfix
- Feature
- **Refactoring (e.g. Style updates, Test implementation, etc.)**
- Add eslinit rules for cypress tests
- Fix code style

Add eslint rules for cypress

---

.github/workflows/ci.yml
CHANGELOG.md
config/bigbluebutton.php
database/seeders/ServerSeeder.php
docs/docs/development/04-workflow.md

- Bugfix
- Feature
- Replace `TESTING_BBB` env variable for integration tests with `BBB_TEST_SERVER_HOST` and `BBB_TEST_SERVER_SECRET`

Refactor TESTING_BBB env variable

---

resources/js/components/RoomHeader.vue
resources/js/components/RoomMembershipButton.vue

- **Bugfix**
- Feature
- Move logic to display room favorites and room membership button to parent component

Fix room favorite button shown to guests

---

app/Http/Controllers/api/v1/RoomController.php
tests/Backend/Feature/api/v1/Room/RoomTest.php

- **Bugfix**
- Feature
- Apply non-expert settings of the room type

Apply non-expert settings of the room type

---

resources/js/views/RoomsView.vue

- **Bugfix**
- Feature
- Fix different handling of 404 errors when visiting and reloading room view

Fix different handling of 404 errors in RoomsView

---

resources/js/components/RoomHeader.vue
resources/js/components/RoomMembershipButton.vue
resources/js/views/RoomsView.vue

- **Bugfix**
- Feature
- Fix missing access code handling in room membership button

Fix access code handling

---

resources/js/components/RoomTabFiles.vue
resources/js/components/RoomTabFilesDeleteButton.vue
resources/js/components/RoomTabFilesEditButton.vue

- **Bugfix**
- Feature
- Fix error handling for deleting room file that does not exist
- Fix error handling for editing room file that does not exist

Fix room file error handling

---

resources/js/components/RoomTabMembersBulkDeleteButton.vue
resources/js/components/RoomTabMembersBulkEditButton.vue

- **Bugfix**
- Feature
- Show error message for users errors inside bulk edit dialog

Fix no error message shown on users errors (bulk edit)

---

resources/js/components/RoomTabSection.vue

- **Bugfix**
- Feature
- Fix not room tab selected on permission or room role change

Fix not room tab selected on permission or room role change
