THM-Health/PILOS

.eslintrc.js, app/User.php, database/seeds/RolesAndPermissionsSeeder.php, resources/js/components/RawText.vue, resources/js/lang/de/settings.js, resources/js/lang/en/settings.js, resources/js/views/settings/roles/View.vue, tests/Frontend/App.spec.js, tests/Frontend/views/settings/roles/View.spec.js, tests/Unit/UserTest.php
- **Bugfix**
- Feature
- Changed room limit calculation to a simpler algorithm
- Added room limit calculation help modal to role settings
- Added raw-text component, to bypass no-raw-text rule of eslint in special cases where a translation isn't needed
- Removed unnecessary user default role and added unlimited room limit to admin role
- Fix tests
=> 59 fix room limit calculation

CHANGELOG.md, app/Http/Controllers/api/v1/RoomTypeController.php, resources/js/views/rooms/Index.vue, tests/Feature/api/v1/Room/RoomTypeTest.php, tests/Frontend/views/rooms/Index.spec.js
- **Bugfix**
- Feature
- Room types filter only shows searchable room types for users without permission *rooms.viewAll*
=> 138 Hide room types from search

CHANGELOG.md, database/migrations/2021_05_31_164031_extend_room_id.php, routes/web.php, tests/Unit/Console/ImportGreenlightTest.php
- **Bugfix**
- Feature
- Extended room id to support ids of new greenlight versions (e.g. xxx-xxx-xxx-xxx)
=> Extend room id to support new greenlight room ids

CHANGELOG.md, app/Http/Controllers/api/v1/MeetingController.php, app/Http/Controllers/api/v1/RoomController.php, app/Room.php, app/Server.php, composer.json, config/bigbluebutton.php, tests/Feature/api/v1/MeetingTest.php, tests/Feature/api/v1/Room/RoomStatisticTest.php, tests/Feature/api/v1/Room/RoomTest.php
- **Bugfix**
- **Feature**
- Refactoring the creation of meetings when starting a new room to prevent users from joining a meeting that is not yet ready and to prevent the cronjob from checking these meetings, which could lead to them being deleted immediately
- Add atomic locks for starting a room to prevent users from simultaneously starting the same room, which could lead to two meeting beeing opend
=> Add meeting starting status and atomic lock

.github/workflows/ci.yml
- Bugfix
- Feature
- **Refactoring** 
- Remove php 7.3 from CI
- Add php 8.0 to CI
=> Bump minimal php version in ci to 7.4

CHANGELOG.md, config/auth.php, tests/Feature/api/v1/LdapLoginTest.php
- **Bugfix**
- Feature
- Adding sync_existing (https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#sync-existing-records) to overwrite guid for existing users by using the username to uniquely identify the user
=> Fix error 500 on login

CHANGELOG.md, jest.config.js, resources/js/app.js, resources/js/components/Room/DeleteRoomComponent.vue, resources/js/components/Room/FileComponent.vue, resources/js/components/Room/HistoryComponent.vue, resources/js/components/Room/MembersComponent.vue, resources/js/components/Room/SettingsComponent.vue, resources/js/components/Room/TokensComponent.vue, resources/js/components/RoomType/RoomTypeSelect.vue, resources/js/directives/hide-tooltip.js, resources/js/views/meetings/Index.vue, resources/js/views/rooms/Index.vue, resources/js/views/rooms/OwnIndex.vue, resources/js/views/rooms/View.vue, resources/js/views/settings/roles/Index.vue, resources/js/views/settings/roomTypes/Index.vue, resources/js/views/settings/serverPools/Index.vue, resources/js/views/settings/servers/Index.vue, resources/js/views/settings/servers/View.vue, resources/js/views/settings/users/Index.vue, tests/Frontend/directives/HideTooltip.spec.js, tests/Frontend/setup.js
- **Bugfix**
- **Feature**
- Add custom directive v-tooltip-hide-click to close tooltip on click
Tooltip was not hidden if button was disabled. The disabling was mostly caused by user actions, so hiding the tooltip on a user-action resolves 99% of the occurrences. The issue only persists if the disabled attribute is caused by something else than a user-action (e.g. background reload)
=> Add custom directive to close tooltip on click

CHANGELOG.md, app/Http/Resources/Room.php, resources/js/components/Room/RoomComponent.vue, resources/js/components/Room/RoomStatusComponent.vue, resources/js/lang/de/rooms.js, resources/js/lang/en/rooms.js, resources/js/views/rooms/Index.vue, resources/js/views/rooms/OwnIndex.vue, resources/sass/app/_room.scss, resources/sass/theme/default/_variables.scss, resources/sass/theme/thm/_variables.scss, tests/Feature/api/v1/Room/RoomTest.php, tests/Frontend/components/Room/RoomStatus.spec.js, tests/Frontend/views/rooms/Index.spec.js, tests/Frontend/views/rooms/OwnIndex.spec.js
- Bugfix
- **Feature**
- Add meeting status to general room attributes
- Show meeting running status on own rooms page and in find room / all rooms list
- Add option in theme to show a red dot if meeting not running ($showRoomClosedIndicator in resources/sass/theme/{THEME}/_variables.scss)
=> Show meeting status in overview and lists

docker-compose-dev.yml
- **Bugfix**
- Feature
- The statement « links » is deprecated since at least 5 or 6 years ago and seems useless is this specific development case ( https://docs.docker.com/network/links/ )
- This also permit to developers that uses podman rather than docker to work on this project, because podman doesn't support this very old deprecated statement ( https://github.com/containers/podman/issues/11717 )
=> Remove the deprecated Docker « links » statement for phpmyadmin/phpldapadmin

CHANGELOG.md, app/Http/Requests/RoleRequest.php, tests/Feature/api/v1/RoleTest.php
- Bugfix
- **Feature**
- Allow more different characters for role names
Previously only alphanumeric characters, hyphens and underscores were allowed
=> Allow more chars for role name

docker/app/Dockerfile
This remove the wait time of 60s while building the image due to script deprecation. This follows instruction linked at 'https://github.com/nodesource/distributions'
See laravel sail: https://github.com/laravel/sail/pull/613/commits/eeb652ddffb60809b031d6a01cf909d9f51038ff
=> Change node source repository

CHANGELOG.md, docker/app/Dockerfile
- **Bugfix**
- Feature
- Bump docker base image to PHP 8.3
- Upgrade xdebug
=> Upgrade docker base image

CHANGELOG.md, app/Http/Controllers/MeetingController.php, app/Http/Controllers/api/v1/ApplicationController.php, app/Http/Controllers/api/v1/MeetingController.php, app/Http/Requests/UpdateSetting.php, app/Http/Resources/ApplicationSettings.php, app/Http/Resources/Meeting.php, app/Http/Resources/Room.php, app/Services/RoomService.php, app/Services/ServerService.php, lang/de/settings.php, lang/en/settings.php, lang/fr/settings.php, resources/js/components/RoomTabHistory.vue, resources/js/views/settings/Config.vue, tests/Feature/api/v1/Room/RoomStatisticTest.php, tests/Feature/api/v1/Room/RoomTest.php, tests/Feature/api/v1/SettingsTest.php, tests/Unit/Console/BuildHistoryTest.php, tests/Unit/ServerTest.php
- Bugfix
- Feature
- Remove global attendance recording setting
Since adding an option to set the attendance recording for each room type, this should be removed to simplify the code.
=> Remove global attendance recording setting

CHANGELOG.md, app/Services/BigBlueButton/LaravelHTTPClient.php, composer.lock, package-lock.json, tests/Unit/MeetingTest.php
- **Bugfix**
- Feature
- Fix starting room with files fails if scalelite server is used 
- Bump Dependencies
Order of calling the Laravel HTTP Client caused an invalid Content-Type causing scalelite to fail the request
=> Fix starting room with files fails if scalelite server is used

CHANGELOG.md, app/Http/Controllers/api/v1/ServerController.php, app/Models/Server.php, app/Services/LoadBalancingService.php, config/bigbluebutton.php, database/factories/ServerFactory.php, database/migrations/2024_03_06_152142_add_health_counters_to_servers_table.php, database/seeders/ServerSeeder.php, tests/Feature/api/v1/ServerTest.php, tests/Unit/Console/PollServerTest.php, tests/Unit/ServerPoolTest.php, tests/Unit/ServerServiceTest.php, tests/Unit/ServerTest.php
- Bugfix
- Feature
- Rename env option `BBB_SERVER_HEALTHY_THRESHOLD`to `BBB_SERVER_ONLINE_THRESHOLD`
- Rename env option `BBB_SERVER_UNHEALTHY_THRESHOLD`to `BBB_SERVER_OFFLINE_THRESHOLD`
Rename options to a less misleading name
=> Rename env options for server health

CHANGELOG.md, app/Http/Controllers/api/v1/RoomTypeController.php, app/Http/Requests/RoomTypeRequest.php, app/Http/Resources/RoomType.php, app/Services/MeetingService.php, database/migrations/2024_05_22_101114_add_create_parameters_to_room_types_table.php, lang/de/settings.php, lang/en/settings.php, resources/js/views/settings/roomTypes/View.vue, tests/Feature/api/v1/Room/RoomTest.php, tests/Feature/api/v1/Room/RoomTypeTest.php, tests/Unit/MeetingTest.php
- Bugfix
- **Feature**
- Adds custom create api call parameters in room type settings
- Room settings will be changed according to the custom parameters when the room type is changed.
=> Custom create parameters in room type settings 

lang/de/rooms.php, lang/en/rooms.php, lang/fr/rooms.php, resources/js/components/RoomTabDescription.vue, resources/js/components/TipTapImage.vue
- Bugfix
- **Feature**
- Only allow external image urls with https:// in room description
=> Filter img src attribute

.github/workflows/pull-locales.yml, .github/workflows/upload-locales.yml, README.md, app/Console/Commands/UploadLocalesCommand.php, docs/docs/administration/08-customisation/02-locales.md, tests/Backend/Unit/Console/UploadLocalesTest.php
- **Bugfix**
- Feature
- Other (please describe): **Localisation**
- Adjust link to PoEditor Project for v4
- Adjust artisan command to only upload terms and english locale by default
- Change github workflows to auto pull locales
=> Adjust docs and command for localisation workflow with POEditor in v4

app/Auth/Shibboleth/ShibbolethSessionMiddleware.php, config/services.php, docs/docs/administration/07-advanced/01-external-authentication.md, tests/Backend/Feature/api/v1/ShibbolethTest.php
- Bugfix
- **Feature**
- Adds a new environment variable `SHIBBOLETH_SESSION_CHECK_ENABLED` defaulting to `true`. If set to `false` checking shibboleth session validity on every request is disabled. This is necessary for setups where not every request is routed through Apache.
=> Add env variable to disable shib session checking middleware

resources/js/components/RoomTabMembers.vue
- **Bugfix**
- Feature
- Hide bulk edit/delte room member checkboxes if user does not have permission to manage room
=> Hide bulk edit/delte room member checkboxes if user does not have permission to manage room

resources/js/views/RoomsIndex.vue
- **Bugfix**
- Feature
- Fixes wrong numer of rooms shown on initial load of rooms index page
=> Fix wrong number of rooms shown on initial load of rooms index page

routes/web.php
When users only have two letters as firstname (which is the case in our user base and occurrs more frequently when the title 'Dr.' is part of the name) the regex fails for the room. These rooms have a format like: `dr--asd-wer-qwe`.
This commit fixes the regex.
- **Bugfix**
=> Fix greenlight room redirects for users with two letter firstnames
